# Generated by Django 3.1 on 2023-10-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VegHotel',
            fields=[
                ('Hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('Hotel_name', models.CharField(max_length=250, unique=True)),
                ('Hotel_image', models.ImageField(max_length=250, upload_to='images/')),
                ('Hotel_Address', models.CharField(max_length=255)),
            ],
        ),
    ]
