# Generated by Django 3.1 on 2023-10-12 16:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foodieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegFoodItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=250)),
                ('Item_image', models.ImageField(blank=True, default=None, max_length=250, null=True, upload_to='images/')),
                ('Item_price', models.FloatField(blank=True, default=0.0, help_text='Price in INR', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)])),
                ('item_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_name', to='Foodieapp.veghotel')),
            ],
        ),
    ]
