# Generated by Django 3.1 on 2023-10-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foodieapp', '0002_vegfooditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegfooditems',
            name='hotel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='Foodieapp.veghotel'),
        ),
    ]
