# Generated by Django 3.1 on 2023-10-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodieapp', '0003_auto_20231012_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegfooditems',
            old_name='hotel_name',
            new_name='hotel_Name',
        ),
    ]
