# Generated by Django 3.1 on 2023-10-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodieapp', '0005_auto_20231012_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegfooditems',
            old_name='hotel_Name',
            new_name='hotel',
        ),
    ]
