# Generated by Django 3.1 on 2023-10-13 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodieapp', '0006_auto_20231013_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegfooditems',
            old_name='hotel',
            new_name='Hotel_name',
        ),
    ]
