# Generated by Django 3.1 on 2023-10-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodieapp', '0008_chats_chatsitemname_nonvegfooditems_nonveghotel_sweets_sweetsitemname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='Hotel_id',
            new_name='Chats_Hotel_id',
        ),
        migrations.RenameField(
            model_name='nonveghotel',
            old_name='Hotel_id',
            new_name='Nonveg_Hotel_id',
        ),
        migrations.RenameField(
            model_name='sweets',
            old_name='Hotel_id',
            new_name='Sweets_Hotel_id',
        ),
    ]
