# Generated by Django 3.1 on 2023-10-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodieapp', '0010_auto_20231013_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatsItemName',
            new_name='ChatsItem',
        ),
        migrations.RenameModel(
            old_name='SweetsItemName',
            new_name='SweetsItem',
        ),
    ]
